export const DEMO = "demo"
export const DELE_USER_INFO = "dele_user_info"
export const SAVE_USER_INFO = "save_user_info"
export const SAVE_TITLE = "save_title"
export const DELE_TITLE = "delet_title"
export const SAVE_GOODS_LIST = "save_goods_list"
export const SAVE_CATEGORY_LIST = "save_category_list"